### ISSUE TITLE
Test naming

### ISSUE THREAD

**Issue by CrisKrus** [alu0101238944/kata-is-strong-password#2]
Igual ha pasado tanto tiempo desde que has hecho esto que no lo recuerdes bien, pero quería preguntarte sobre el nombre del test. ¿Por qué en este test el nombre no dice que regla esta testando? Veo que en el resto si que dice la regla que quieres probar como "al menos tiene un digito" pero en este solamente dice: "devuelve verdadero"

https://github.com/alu0101238944/kata-is-strong-password/blob/35e623161ed17d9eb738df8239c3e973a3d61599/test_is_strong_password.py#L9

**Comment by alu0101238944** [comment]
Hola Cristian. Lo cierto es que en esta kata quise probar una manera, sugerida en el libro de Diseño Ágil con TDD, de abordar aquellos problemas relativos a funciones booleanas que comprueban una serie de condiciones.

Este método consiste en poner al principio un ejemplo de cadena válida que debe ser aceptada como test, verlo en rojo y, para hacer que pasara, simplemente retornar true en la función que se implementa. A continuación, para cada condición que se quiera desarrollar, se debe crear un nuevo test cuya entrada a la función cumpla todos los requisitos excepto aquel que se está comprobando; y en esta situación, la función evidentemente debe devolver false. Sin embargo, hasta que no se codifique la comprobación deseada, retornará true. De esta manera, cada test tiene únicamente un motivo para fallar: que no se esté comprobando la condición que se pretende implementar.

Ahora viendo el nombre del primer test, no me termina de parecer uno bueno. Me echa un poco para atrás el "return_true". El nombre del test debería dar más pistas sobre la regla de negocio, y no describir literalmente la implementación que encierra. Es por ello que creo que se puede abusar del lenguaje y cambiar el nombre del test por algo del estilo: "test_strong_password_is_valid" o "test_strong_password_is_accepted". De esta manera, el primer test describe el comportamiento ante una contraseña fuerte, y en los siguientes test se describen aquellas condiciones que hacen que una contraseña lo sea.

No sé cómo lo verás, ¿qué te parece?
Gracias por todo Cristian,
Saludos

**Comment by CrisKrus** [comment]
Hola! Si, justamente lo decía por eso el `return_true` no ayuda a comprender la regla de negocio que cumple. Me parece buena opción el `is_valid` por ejemplo.

Gracias por la explicación!

**Comment by alu0101238944** [comment]
Gracias a ti Cristian! Lo modifico y cierro el issue :D
